//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBooks.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public Nullable<int> CountInShop { get; set; }
        public Nullable<int> CountInStock { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
